const categories = [
	"Overall",
	"Attack",
	"Defence",
	"Strength",
	"Hitpoints",
	"Ranged",
	"Prayer",
	"Magic",
	"Cooking",
	"Woodcutting",
	"Fletching",
	"Fishing",
	"Firemaking",
	"Crafting",
	"Smithing",
	"Mining",
	"Herblore",
	"Agility",
	"Thieving",
	"Slayer",
	"Farming",
	"Runecraft",
	"Hunter",
	"Construction",
	"League points",
	"Bounty hunter hunter",
	"Bounty hunter rogue",
	"Clue scroll (all)",
	"Clue scroll (beginner)",
	"Clue scroll (easy)",
	"Clue scroll (medium)",
	"Clue scroll (hard)",
	"Clue scroll (elite)",
	"Clue scroll (master)",
	"Last man standing",
	"Sire",
	"Alchemical hydra",
	"Barrows chests",
	"Bryophyta",
	"Callisto",
	"Cerberus",
	"Chambers of xeric",
	"Chambers of xeric challenge mode",
	"Chaos elemental",
	"Chaos fanatic",
	"Commander zilyana",
	"Corporeal beast",
	"Crazy archaeologist",
	"Dagannoth prime",
	"Dagannoth rex",
	"Dagannoth supreme",
	"Deranged archaeologist",
	"General graardor",
	"Giant mole",
	"Grotesque guardians",
	"Hespori",
	"Kalphite queen",
	"King black dragon",
	"Kraken",
	"Kreearra",
	"Kril tsutsaroth",
	"Mimic",
	"Nightmare",
	"Obor",
	"Sarachnis",
	"Scorpia",
	"Skotizo",
	"Gauntlet",
	"Corrupted gauntlet",
	"Theatre of blood",
	"Thermonuclear smoke devil",
	"Tz-kal-zuk",
	"Tz-tok-jad",
	"Venenatis",
	"Vetion",
	"Vorkath",
	"Wintertodt",
	"Zalcano",
	"Zulrah",
]

const Category = {
	OVERALL: categories[0],
	ATTACK: categories[1],
	DEFENCE: categories[2],
	STRENGTH: categories[3],
	HITPOINTS: categories[4],
	RANGED: categories[5],
	PRAYER: categories[6],
	MAGIC: categories[7],
	COOKING: categories[8],
	WOODCUTTING: categories[9],
	FLETCHING: categories[10],
	FISHING: categories[11],
	FIREMAKING: categories[12],
	CRAFTING: categories[13],
	SMITHING: categories[14],
	MINING: categories[15],
	HERBLORE: categories[16],
	AGILITY: categories[17],
	THIEVING: categories[18],
	SLAYER: categories[19],
	FARMING: categories[20],
	RUNECRAFT: categories[21],
	HUNTER: categories[22],
	CONSTRUCTION: categories[23],
	LEAGUE_POINTS: categories[24],
	BOUNTY_HUNTER_HUNTER: categories[25],
	BOUNTY_HUNTER_ROGUE: categories[26],
	CLUE_SCROLL_ALL: categories[27],
	CLUE_SCROLL_BEGINNER: categories[28],
	CLUE_SCROLL_EASY: categories[29],
	CLUE_SCROLL_MEDIUM: categories[30],
	CLUE_SCROLL_HARD: categories[31],
	CLUE_SCROLL_ELITE: categories[32],
	CLUE_SCROLL_MASTER: categories[33],
	LAST_MAN_STANDING: categories[34],
	SIRE: categories[35],
	ALCHEMICAL_HYDRA: categories[36],
	BARROWS_CHESTS: categories[37],
	BRYOPHYTA: categories[38],
	CALLISTO: categories[39],
	CERBERUS: categories[40],
	CHAMBERS_OF_XERIC: categories[41],
	CHAMBERS_OF_XERIC_CHALLENGE_MODE: categories[42],
	CHAOS_ELEMENTAL: categories[43],
	CHAOS_FANATIC: categories[44],
	COMMANDER_ZILYANA: categories[45],
	CORPOREAL_BEAST: categories[46],
	CRAZY_ARCHAEOLOGIST: categories[47],
	DAGANNOTH_PRIME: categories[48],
	DAGANNOTH_REX: categories[49],
	DAGANNOTH_SUPREME: categories[50],
	DERANGED_ARCHAEOLOGIST: categories[51],
	GENERAL_GRAARDOR: categories[52],
	GIANT_MOLE: categories[53],
	GROTESQUE_GUARDIANS: categories[54],
	HESPORI: categories[55],
	KALPHITE_QUEEN: categories[56],
	KING_BLACK_DRAGON: categories[57],
	KRAKEN: categories[58],
	KREEARRA: categories[59],
	KRIL_TSUTSAROTH: categories[60],
	MIMIC: categories[61],
	NIGHTMARE: categories[62],
	OBOR: categories[63],
	SARACHNIS: categories[64],
	SCORPIA: categories[65],
	SKOTIZO: categories[66],
	GAUNTLET: categories[67],
	CORRUPTED_GAUNTLET: categories[68],
	THEATRE_OF_BLOOD: categories[69],
	THERMONUCLEAR_SMOKE_DEVIL: categories[70],
	TZ_KAL_ZUK: categories[71],
	TZ_TOK_JAD: categories[72],
	VENENATIS: categories[73],
	VETION: categories[74],
	VORKATH: categories[75],
	WINTERTODT: categories[76],
	ZALCANO: categories[77],
	ZULRAH: categories[78],
}

module.exports = {
	categories, 
	Category
}
